project:
  type: website
  output-dir: docs

format:
  html:   
    code-link:  true
  pdf:    
    pdf-engine: lualatex 
## under website:  add navbar
website:
  title: "jim"
  navbar:
    left: 
      -   index.qmd
      -   about.qmd
      -   text: gist  
          href: https://gist.github.com/jimrothstein/d8de0e42f8547e3a08ee7d1f1e86fb1f

    

##  default?
