project:
  type: website
  output-dir: docs

website:
  title: "jim"
# date: today    today is 'invalid' here; put in each .qmd file?
  navbar:
    left: 
      -   index.qmd
      -   about.qmd
      -   text: gist  
          href: https://gist.github.com/jimrothstein/d8de0e42f8547e3a08ee7d1f1e86fb1f
      -   href: 001_tech_reading.qmd
          text: 001_tech_reading
      -   href: 010_mtcars_basic.qmd
      -   href: 030_quarto_katex_html_references.qmd
      -   href: 040_not_zero.qmd
      -   href: 130_poisson_distribution.qmd
      -   href: 410_bquote_example.qmd
      -   href: 050_bias_variance_tradeoff.qmd
format:
  html:   
    code-link:  true
    theme: cosmo
    css: custom.scss
    toc: true
      #  pdf:    
      # pdf-engine: lualatex 
