project:
  type:   website
  output-dir: docs
  preview:
    port: 4200
    browser: true
    navigate: true
  render:
    -   "*.qmd"

website:
  title: "Notes To Myself"
  description: "Assorted breadcrumbs, ideas that may not be of use"
  repo-url: https://github.com/jimrothstein/
    #repo-actions: [source, edit, issue]
    #site-url: "https://crumplab.com/GPTAttentionPerformance"
  navbar:
    search: true
    left: 
      -   index.qmd
      -   about.qmd
      #  -   about.qmd   no need for about.qmd
      -   text: gist  
          href: https://gist.github.com/jimrothstein/d8de0e42f8547e3a08ee7d1f1e86fb1f
      -   href: posts/001_tech_reading.qmd
      
#          text: 001_tech_reading
#      -   href: posts/010_mtcars_basic.qmd
#          text: 010_mtcars
#      -   href: posts/030_quarto_katex_html_references.qmd
#      -   href: posts/040_not_zero.qmd
#      -   href: posts/130_poisson_distribution.qmd
#      -   href: posts/410_bquote_example.qmd
#      -   href: posts/050_bias_variance_tradeoff.qmd
format:
  html:   
    code-link:  true
    theme: minty
    css: custom.scss
    toc: true
knitr:
  opts_chunk: 
    collapse: true
    comment: "....->" 
execute: 
  freeze: auto
  echo: true
  error: true
  warning: true
  
