---
title: "Tech Reading"
---
\footnotesize

<!--
template has \small font embedded
!pandoc % -f markdown --template ~/dotfiles/proposed_template.latex -V geometry:margin=0.4in --toc-depth=4 -V toc-title="Reading" -o out.pdf ; zathura out.pdf
-->

<!--
urls:  for github markdown 
  [link](/uri "title"),  OR
  <url>
-->


\tableofcontents

<!--
LINK:  [TEXT portion](URL portion)
        <url>

  \url{nytimes.com}
  \href{url}{text}   url itself does NOT print
  \href{nytimes.com}{Click: NY Times}

pandoc:	
  file <- "001_R_stats_tech_reading.md"
  !pandoc % -t latex -V linkcolor:blue -V fontsize=10pt -V geometry:margin=0.4in -o ~/Downloads/print_and_delete/reading.pdf 
  -V toc-title="Read"   is ignored.

-->

As of \today

###	Algorithms & ML

-  Akalin <https://compgenomr.github.io/book/> - very good, genomics
-  [Berkeley, excellent glossary:](https://www.stat.berkeley.edu/~stark/SticiGui/Text/gloss.htm)
-	 Berkeley CRASH  ML <https://mlberkeley.substack.com/p/part-1>
- Bishop (2006)  Ch1 nice intro: <https://www.microsoft.com/en-us/research/uploads/prod/2006/01/Bishop-Pattern-Recognition-and-Machine-Learning-2006.pdf>
-  Breiman,   2 cultures: <https://www.jstor.org/stable/2676681>
-  Chollet, Deep Learning for R (not online, no pdf)  python:   
  <https://docs.google.com/viewer?a=v&pid=sites&srcid=dW10LmVkdS5wa3xzbmxwfGd4Ojc1ODc1ODY2OTZiOTUzOGQ>
-  Compeau:  
    -	great ideas book! <http://compeau.cbd.cmu.edu/>  
    -	<http://compeau.cbd.cmu.edu/programming-for-lovers/> cmu -	ch 8, 9 esp collinear.  
-  Boehmke Hands on ML | <https://bradleyboehmke.github.io/HOML/> Ch 4,5
- Bohm Statistics for Physics <https://www-library.desy.de/preparch/books/vstatmp_engl.pdf> change of variables (SEE 3.4.1, density as volume)
-  Chan, Stanley <https://probability4datascience.com/index.html> more math and uses Likelikhood
-  Davidson  http://qed.econ.queensu.ca/ETM/etm-info.html
-  Deisenroth, Faiesel et al | Math4ML some intution; linear trans,
  distributions <https://mml-book.github.io/book/mml-book.pdf> linear alg book,
  regression (Ch 9), nice intro to ($\Omega,\mathcal{A}, P$) 
  - related videos <https://www.youtube.com/playlist?list=PLkxomGYFWp67infnvPmEcqyQqk0q6ntrY>
-  [Gagolewski Lightweight ML with R](https://lmlcr.gagolewski.com/) iPad, PDF
- Goodfellow et al: <https://www.deeplearningbook.org/> ideas
- Higgens "Practical R Info?" 
  Higgens, <https://bookdown.org/pdr_higgins/rmrwr/> easy to read, range of
  topics (~cookbook)
- Kaplan  2023 <https://mdsr-book.github.io/mdsr3e/> (tidyverse, parsnip,
  links to wikip for all stats)
- Kaplan  2017, 2E <https://dtkaplan.github.io/SM2-bookdown/>
- Kaplan  2021, 2E, Data <https://dtkaplan.github.io/DataComputingEbook/> see
- Kaplan  2020, Calculus with R <https://dtkaplan.github.io/RforCalculus/index.html> mosaic and mosaicCalc packages (fitting to curves)
  ML, chapter 18, plus interesting other chapters
- Lindholm, "Machine Learning:  A first course for engineers" PDF  more math <http://smlbook.org/> <http://smlbook.org/book/sml-book-draft-latest.pdf>
- Matloff (Prob book) <https://github.com/matloff/probstatbook/blob/master/ProbStatBookW21.pdf> \
  SEE 15.2 for logistic; var transform
- mcelreath: <https://github.com/rmcelreath/stat_rethinking_2022> (videos)
- Molnar <https://christophm.github.io/interpretable-ml-book/> Ch 5.2 logistical regression  (explanations!) 
- Oehlert: 
- Random Services <https://www.randomservices.org/random/dist/Transformations.html> 
- Siegrist: <https://stats.libretexts.org/Bookshelves/Probability_Theory/Probability_Mathematical_Statistics_and_Stochastic_Processes_(Siegrist)/>
- Thomas,  Math for ML  ... good lin alg, but quickly gets advanced.  <https://gwthomas.github.io/docs/math4ml.pdf>
- UCLA:  Mixed Models - intro:  <https://stats.oarc.ucla.edu/other/mult-pkg/introduction-to-linear-mixed-models/>
- Vasishth: <https://vasishth.github.io/bayescogsci/book/ch-reg.html#sec-logistic>
- Venables http://web.mit.edu/r_v3.4.1/R-intro.pdf (SEE models chapter)
- Wiki: <https://en.wikipedia.org/wiki/Generalized_linear_model#Binary_data>, not easy but through
-	 SciLearn
- [Scott, DS with R, Gentle Intro ](https://bookdown.org/jgscott/DSGI/)
- Kazdan |  normal equations, linear alg<https://www2.math.upenn.edu/~kazdan/312S14/>
- Kazdan, many good references: <https://www2.math.upenn.edu/~kazdan/>

#### Intro to Linear Alg & Models, 

  *  Kuiper, Shonda: simple, clear:   video: <https://www.youtube.com/watch?v=jQkK0XMrAdM>
  *  Race, Shaina gentle intro to lin alg:, <https://shainarace.github.io/LinearAlgebra/index.html>
  *  Thomas, Garrett, Math for ML, Berkeley  https://gwthomas.github.io/docs/math4ml.pdf
  *  Bendixcarstensen.com, with R & matrix models (practical; try not use api pkg) http://www.bendixcarstensen.com/APC/linalg-notes-BxC.pdf
  *   Rafael genomics - Chapter 4 matrix  (his older stuff is better, but not
    best organization)
  *   Rafael, Book2: <http://rafalab.dfci.harvard.edu/dsbook-part-2/> (2020?), esp
    Linear Models and ML chapters
  *   Gallier,  advanced linear alg <https://www.seas.upenn.edu/~cis5150/linalg-I.pdf>


#### Logistic Regression (binary response)

$$  
\Pr(y) \sim \binom{n}{y}\theta^y(1-\theta)^{n-y} 
$$
$$
\Pr(y=1)=\theta=\text{logit}^{-1}(\beta_0+\beta_1x_1+\beta_2x_2+...+\beta_7x_7)
$$
 
- Prerequisite:	  Ease going from quantile function to CDF, and back. 
- Difference:   binomial variable, y, =1 and Pr(Y=1) 
- Difference:   p(y=m | x) conditional class probability vs p(y | x), where m repsents a 'class', given x
- Model y vs model log-odds (y)
- Reason for modeling mean
- Transformations of RV

 SEE  :

-  <https://en.wikipedia.org/wiki/Quantile_function>
-   Vasishth, 
- Interpretable ML, Chapter 5.2 
- <https://stats.stackexchange.com/questions/374452/family-of-glm-represents-the-distribution-of-the-response-variable-or-residuals/374461#374461>
- <https://www.theanalysisfactor.com/link-functions-and-errors-in-logistic-regression/>
- <https://www.randomservices.org/random/dist/Transformations.html>


#### QUARTO & CSS | SCSS

::: postbox 
- READ discussions:  <https://github.com/quarto-dev/quarto-cli>
:::
- <https://github.com/mine-cetinkaya-rundel/test-website>
- Rstudio community | SCSS: <https://community.rstudio.com/t/quarto-markdown-list-and-blank-line/160693/4>


### exit
```{r}
knitr::knit_exit()

```

### Recents 
-   Bruno, Modern Stats with Tidyverse (Bruno)Bruno Rodrigues <http://modern-rstats.eu/> (web)
only)
-   [Keyes, R Without Statistics](https://book.rwithoutstatistics.com/index.html)
-   Racket:  HTDP <https://htdp.org/2020-5-6/Book/part_prologue.html>
-   McElreath, fantastic:  <https://www.youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus>


###	BookClub
- Janssens, DS at Command Line: <https://www.datascienceatthecommandline.com/2e/>
- Hadley, <https://mastering-shiny.org/>
- R, javascript + shiny <https://book.javascript-for-r.com/>
- HTTP Testing (book) <https://books.ropensci.org/http-testing/>
- [Deisenroth, et al  Math for ML ] <https://mml-book.github.io/book/mml-book.pdf>
- [Chan, Intro Probability for DS](https://probability4datascience.com/index.html)
- [Meier, ANOVA + MIXED EFFECTS]<https://people.math.ethz.ch/~meier/teaching/anova/index.html>


### R - always learn something new:
  *  Burns, R Inferno (not intro book)
  *  Peng, <https://bookdown.org/rdpeng/rprogdatascience/>
	*  Peng, <https://bookdown.org/rdpeng/RProgDA/>
  *  Peng <https://jhu-advdatasci.github.io/2018/>
  *  Hadley, <https://r4ds.had.co.nz/index.html>
  *	 [Jennybc (book)](https://stat545.com/index.html) [wtf](https://rstats.wtf/) [git](https://happygitwithr.com/)
  *  Gillespie, Lovelace (2016) <https://bookdown.org/csgillespie/efficientR/>
  *  Matloff:  Art of R Programming (2011)
  *  Matloff: <https://github.com/matloff/TidyverseSkeptic>
  *  de Jong, Intro to Data Cleaning  <https://cran.r-project.org/doc/contrib/de_Jonge+van_der_Loo-Introduction_to_data_cleaning_with_R.pdf>
-	Grolemund,  2014 <https://rstudio-education.github.io/hopr/>
  

### R - Documentation (can beat searching !)
	
*  official R CRAN: <https://cran.r-project.org/manuals.html>
	-	R intro:  <https://cran.r-project.org/doc/manuals/r-release/R-intro.html>
	-	R Lang:	<https://cran.r-project.org/doc/manuals/r-release/R-lang.html>
-	 <https://design.tidyverse.org>
-   [ethz](https://stat.ethz.ch/R-manual/R-devel/library/)

### R - graphics (base:: is main package)

-    <https://rdrr.io/r/graphics/par.html>
*   R intro Ch 12:	<https://cran.r-project.org/doc/manuals/r-release/R-intro.html#Graphics>
*   internals - Ch 6 graphics (lower level)
*   base Idiot's guide:  <https://rstudio-pubs-static.s3.amazonaws.com/7953_4e3efd5b9415444ca065b1167862c349.html>
*   shipunov - visual statistics, use? <https://stats.libretexts.org/Bookshelves/Introductory_Statistics/Book%3A_Visual_Statistics_Use_R_(Shipunov)>

### Basic Statistics


#### More Intuitive/Explanatory:

  *  [Rossman, know all the basics?   confident? ASK GOOD Q]( https://askgoodquestions.blog/)
  *  Przemyslaw Biecek and Tomasz Burzykowski | different ideas | Ch1, 2 Explanatory Model Analysis | <https://ema.drwhy.ai/>
  *  [ML Berkeley:](https://ml.berkeley.edu/blog/posts/crash-course/part-1/)
  *  Goodfellow et al: <https://www.deeplearningbook.org/> ideas
  *  Guo:  Creative site and book: <https://seeing-theory.brown.edu/#firstPage>
  *  Huntington "The Effect Book" <https://www.theeffectbook.net/index.html>
  *  navarro (learn statistics with r) review lm() and geometric r^2, Ch15, 16
	*  Huntington <https://www.theeffectbook.net/index.html> (intutition?)
*   Taylor, J "Introduction to Error Analysis - 2nd" unique book, error
propogation and calculations.

###     Related to ISLR
*   [Gagolewski Lightweight ML with R](https://lmlcr.gagolewski.com/) iPad
*   <https://cran.r-project.org/doc/contrib/Faraway-PRA.pdf> linear algebra
*   Navarro: Ch 15 <https://learningstatisticswithr.com/>
*   residuals, geometry <https://socialsciences.mcmaster.ca/jfox/Papers/matlib-useR2016.pdf>
*   matlib (vectors):  https://cran.r-project.org/web/packages/matlib/index.html
*   https://github.com/friendly/matlib/
*   Shalizi [2019 Truth About Linear Regression] (http://www.stat.cmu.edu/~cshalizi/TALR/) -deeper/more explanatory. By Ch 11, use of gradient f, matrix derviatives ....
*  Kuiper, Shonda: linear algebra simple, clear:   video: <https://www.youtube.com/watch?v=jQkK0XMrAdM>
*  Race, Shaina gentle intro to lin alg:, < https://shainarace.github.io/LinearAlgebra/index.html  >
*  Videos - Cohort 05: https://www.youtube.com/playlist?list=PL3x6DOfs2NGjbefZellBVB306_z8Wz1Xd

*  Roback: LINE:  <https://bookdown.org/roback/bookdown-BeyondMLR/ch-MLRreview.html#assumptions-for-linear-least-squares-regression>
<https://socialsciences.mcmaster.ca/jfox/Papers/matlib-useR2016.pdf>


*   Friendly... (adv) geometry and statistical methods <https://bityl.co/JdSp>
*   Friendly: <http://friendly.github.io/matlib/articles/data-beta.html>

#### Solid, basic stats intros
  *  Matloff (Prob book) <https://github.com/matloff/probstatbook/blob/master/ProbStatBookW21.pdf>
  *  PSU Course begin with 414 | | no R
    *   <https://online.stat.psu.edu/stat414/>
    *   <https://online.stat.psu.edu/stat462/>
    *   <https://online.stat.psu.edu/stat415/>
  *	 AMS Basic, good intro CLT (but not t)
  *  Dekking, et al Modern Introduction to Probability & Statistics (2005), no R. <https://cis.temple.edu/~latecki/Courses/CIS2033-Spring13/Modern_intro_probability_statistics_Dekking05.pdf>
  *  Frey, Bruce "Statistical Hacks"
  *  [Dalpiaz, David, Univ of IL] ( https://daviddalpiaz.github.io/appliedstats/ )
  *  Lindelov:  Concise R examples of common stat tests.
	*		Lavine, Statistical Thought: https://people.math.umass.edu/~lavine/Book/book.pdf
  *  Siegrist <https://www.randomservices.org/random/index.htmli>
      CLT, stats, linear alg | aka randomservices.org |  ** best book for introducing Math  
  *  Nahim,  Dueling Idiots, harder but real world stats/prob problems (pins
      falling on surfaces)

####	R and Special Topics
	-	Data Science at Command Line (book) https://datascienceatthecommandline.com/2e/chapter-2-getting-started.html
		-	videos: https://www.youtube.com/c/R4DSOnlineLearningCommunity  

####	Blogs
  -  <https://towardsdatascience.com>
  -  R-Blogger
	-  \url{https://rweekly.org/}{rweekly.org}
	-	 https://www.rstudio.com/blog/software-development-resources-for-data-scientists/
	-	 \href{milospopovic.net}{milospopovic}

####  R, the Language: Functional, Standard and Non- Evaluation, Environments, Call Stacks:

  *  Chambers (2008) "Statistics & Computing" (much coverage of R internals)
	\url{https://files.slack.com/files-pri/T6UC1DKJQ-F016BP8QPMG/download/john-chambers-software-for-data-analysis-programming-with-r.pdf?origin_team=T6UC1DKJQ}
  *  Gaslam, Brodie - blog - several good posts
    *   NSE:  <https://www.brodieg.com/2020/05/05/on-nse/>
    *   HP Calculator & Reverse Polish!  <https://www.brodieg.com/2019/01/11/reverse-polish-notation-parsing-in-r/>
    *   Side Effects, Macros:  <https://www.brodieg.com/2019/10/30/visualizing-algorithms/>
  * Gupta, Suraj - <How R Finds objects: https://blog.obeautifulcode.com/R/How-R-Searches-And-Finds-Stuff/>
  * Rnews - Lumley, Macros in R:   <https://www.r-project.org/doc/Rnews/Rnews_2001-3.pdf>
  * Rnews - 2001-2008 has lot of good articles
-	rlist use functional ideas with lists:  <https://renkun-ken.github.io/rlist/>
- tutorial for rlist:  <https://renkun-ken.github.io/rlist-tutorial/>
- Gatto:  <https://github.com/lgatto/TeachingMaterial/blob/master/_R-functional-programming/functional-programming.pdf>


### Linear Algebra (as mathematics)

  *  Beezer Linear Algebra (easier?)
  *  Herve Adbi | lin alg| no R, no stat, starts simple but gets to decomposition.
  *  Strang, Linear Algebra (classic)
  *  Artin, Michael "Algebra"  - readable ?

#### Haskell
-	fairly gentle Haskell intro: https://www.cantab.net/users/antoni.diller/haskell/units/unit02.html
-	Haskell book:	http://book.realworldhaskell.org/read/

### Other book stats/R books:

  *  Hannay (=rbassett) read, (avoid pkgs ch 11, 12) | <https://faculty.nps.edu/rbassett/_book/>
  *  Ismay modern dive (2020)
  *  Kaplan (2017) ch 6.5 <https://dtkaplan.github.io/SM2-bookdown/>  (wordy,
	but exposes nuances)
  *	 Matloff(2020) book
  *	 Mcelreath (videos)
  *	 PENG  | 	art of ... (2017) ch 6.5  <https://bookdown.org/rdpeng/artofdatascience/> | r4ds			 (2019)	ch 9.5
  * 	mosaic ch 5.6, ch 24

### More advanced regession/modeling books

    -   Cosmo Shalizi:  excellent:
    -  [2019 Truth About Linear Regression] (http://www.stat.cmu.edu/~cshalizi/TALR/) -deeper/more explanatory. By Ch 11, use of gradient f, matrix derviatives ....
    -  Shalizi-2021: Advanced Data Analysis From Elem Point of View:
        <http://www.stat.cmu.edu/~cshalizi/ADAfaEPoV/ADAfaEPoV.pdf>
    -  <http://www.stat.cmu.edu/~cshalizi/mreg/15/>
-  Davidson (Econometric) -  Ch 1, 2
- [ISLRv2:](https://web.stanford.edu/~hastie/ISLRv2_website.pdf)
		-	videos: <https://www.youtube.com/c/R4DSOnlineLearningCommunity>
-  MATLOFF (1st book) |	ch3 - lot of useful prproperties of x,y  | 	ch 7  - affine transformations
*  Efron, Hastie "Computer Age Statistical Inference"  (advanced, but chapter intros put techniques into perspective), no R.
*  Kuhn (2019): https://bookdown.org/max/FES/
*  RAFAEL  			dsbook - ch 17.4, ch 18.3.4
*  **Roback/Legler Beyond Multiple Linear Regression: (2021)**_ <https://bookdown.org/roback/bookdown-BeyondMLR/>
      (Replaces BYSH) introduces likelihood; ch6 - logistic worked problem
*	 Siegrist (aka random services.org) * random| (3)expected value 1..11 and 	|(5) random samples 1-8 (t-dist)
* Taubes, linear alg, statistics,  http://people.math.harvard.edu/~knill/teaching/math19b_2011/handouts/chapters1-19.pdf
      Biology?  math?  probability?   Think this is really an ideas book; not as easy as may appear.
* Liquet <https://deeplearningmath.org/>  lots of math


###     BAYES
-	\href{https://arbital.com/p/bayes_rule/}{Arbital, wiki-like}
-	 Barber, David:	Bayesian Reasoning & ML (examples): \href{http://web4.cs.ucl.ac.uk/staff/D.Barber/textbook/020217.pdf}{Barber}
-	 Clyde, Mine et al Intro To Bayesian Thinking  (R,intuitive, online only)
-  Downey, Allen \href{"Thinking Bayes" https://www.greenteapress.com/thinkbayes/thinkbayes.pdf}{2012 pdf, clear intutive, but python)}
-  Davidson-Pilon Bayesian for Hackers  python, but ideas seem well
presented.
-	Dekking \href{https://cis.temple.edu/~latecki/Courses/CIS2033-Spring13/Modern_intro_probability_statistics_Dekking05.pdf}{Dekking Modern Intro}
-	Gimenez:  Easy Stats (examples)
-  Kurz: Statistial Rethinking reCoded (Bayesian) \url{https://bookdown.org/content/4857/#how-to-use-and-understand-this-project} (R, meant as supplement to McElreath)
-	 Johnson, Ott et al: \href{https://www.bayesrulesbook.com/index.html}{BayesRules !	}
-	Lavine  (tutorial) https://people.math.umass.edu/~lavine/whatisbayes.pdf
-	
-	McElreath:	book, videos  Statistical Rethinking \href{http://xcelab.net/rm/statistical-rethinking/}{info}
-  paulvanderlake (many R resources) 2012 ThinkBayes \href{https://paulvanderlaken.com/2017/08/31/data-science-machine-learning-statistics-resources/}{paulvanderlake}
-	Taubes, Lectures 1-19	\href{https://people.math.harvard.edu/~knill/teaching/math19b_2011/handouts/chapters1-19.pdf}{Lectures 1-19}

<!--
			Repeat using `itemize`
\begin{itemize}
\item {Aaronson, Scott: \url{https://www.scottaaronson.com/qclec.pdf} 	Information Theory:  CS, Quantum, Bayesian, linear algebra, Probability}  
\item {Clyde, Mine et al Intro To Bayesian Thinking	(R,intuitive, online only) }  
\item { Downey, Allen "Thinking Bayes" https://www.greenteapress.com/thinkbayes/thinkbayes.pdf  (2012 pdf, clear intutive, but python) }  
\item {Davidson-Pilon Bayesian for Hackers  python, but ideas seem well 	presented.}
\item { Johnson, Ott et al:  https://www.bayesrulesbook.com/index.html (online, item 	no pdf) }
\item {Kurz: Statistial Rethinking reCoded (Bayesian) \url{https://bookdown.org/content/4857/#how to-use-and-understand-this-project} (R, meant as supplement to McElreath)}
\item {Paulvanderlake (many R resources) 2012 ThinkBayes}
\end{itemize}
-->

####	2nd Bayes books | Advanced or  Interesting Ideas
-	 Aaronson, Scott: \url{https://www.scottaaronson.com/qclec.pdf}
Information Theory:  CS, Quantum, Bayesian, linear algebra, Probability
- Cunningham, Scott:   Mixtape: Causal Inference \href{https://mixtape.scunning.com/}{mixtape}
-	Hunington-Klein The Effect Book wordy \href{https://www.theeffectbook.net/index.html}{Effect Book}
-	Gelman: DBA3 \href{http://www.stat.columbia.edu/~gelman/book/BDA3.pdf}{Gelman DBA 3}
-	\href{http://theanalysisofdata.com/probability/0_1.html}{Lebanon, Guy
Analysis of Data;  more advanced math, some measure}

#### Shiny

<!-- {{{ -->
	-	R, javascript + shiny https://book.javascript-for-r.com/
	-	Hadley, https://mastering-shiny.org/
	-	https://engineering-shiny.org/
	-	HTTP Testing (book) https://books.ropensci.org/http-testing/

<!-- }}} -->
   
####  Latex (.tex, latex, not knitr, markdown, pandoc)

  *  [https://learnbyexample.github.io/customizing-pandoc/](Good tips)
  *  \href{https://ctan.math.illinois.edu/info/lshort/english/lshort.pdf}{Not So Short Introduction}
  *  Latex:  Latex in 24 hours (iPad)
  *   <https://www.physicsread.com/latex/>  examples of typical useage
  *  https://mirrors.rit.edu/CTAN/info/beginlatex/html/intro.html#intro
  *  wikibooks:     https://en.wikibooks.org/wiki/LaTeX/Document_Structure
  *  http://ctan.imsc.res.in/info/first-latex-doc/first-latex-doc.pdf
  *  https://texfaq.org/FAQ-man-latex
  *  LuaTex Manual:   http://www.pragma-ade.com/general/manuals/luatex.pdf 
  *  LuaTex Background Overleaf:  https://www.overleaf.com/learn/latex/Articles/An_Introduction_to_LuaTeX_(Part_1)%3A_What_is_it%E2%80%94and_what_makes_it_so_different%3F
  *  Fontspec pkg (for LuaTex) https://mirrors.rit.edu/CTAN/macros/unicodetex/latex/fontspec/fontspec.pdf
	*  Video:   Michelle ... (very clear!)
	

	Math Mode

	*  AMS math  documentation
		 \href{https://www.latex-project.org/help/documentation/amsldoc.pdf}{2017
		 version on ipad}
	*  https://www1.cmc.edu/pages/faculty/aaksoy/latex/latexthree.html#
	*  http://web.mit.edu/rsi/www/pdfs/math.pdf
	*  https://www.atqed.com/latex-column-vector

### Good Technical Reading
  *  Linux:  Archiwiki, Debian, FreeBSD
  *  Gross, Ash et al "Elliptical Tales" - very readable, but must think!
      (515.983 | ASH | 2012)
	*  Linux- insides: https://0xax.gitbooks.io/linux-insides/content/
  *  Seefeld, et al Biology & R | https://cran.r-project.org/doc/contrib/Seefeld_StatsRBio.pdf
-	Robert Sedgewick and Kevin Wayne (essential info ... serious programmers) https://algs4.cs.princeton.edu/home/

#### ZSH
  *  Janssens, DS at Command Line: https://www.datascienceatthecommandline.com/2e/  
        Great way to improve zsh, CLI skills.
	*		Rothgar  Mastering ZSH: https://github.com/rothgar/mastering-zsh 


####	REGEX  
Focus:  **grep -P,  regex usage**:\

- https://linuxize.com/post/regular-expressions-in-grep/#grep-regular-expression
	(overview, not bad place to start)	
-	another overview:	https://bsd.org/regexintro.html
-	!wikipidia - several excellent articles and background.
-	GNU grep documentation:
	https://www.gnu.org/savannah-checkouts/gnu/grep/manual/grep.html#Top
- **wikipedia articles!**  
	Because touch upon many issues: quoting, expansions, quasi-quotation,
	recursion, definitions which I have stumbled accross but never really
	understood at appropriate abstraction.  Now it may clarify why do what we do
	and why the nomenclature is the way it is.
-	!so [regex] FAQ: https://stackoverflow.com/tags/regex/info (specific question (else can get lost in all the permutations.)

Too comprehensive? (docs that cover flavors, usage in languages are too
confusing to me)
	
-	(Regex | Jan Goyvaerts) https://www.regular-expressions.info/tutorial.html (regex buddy)
- https://www.regular-experssions.mobi
-	\href{https://learnbyexample.github.io/tags/regular-expressions/}{https://learnbyexample.github.io - some very intuitive arguments}
-	(iPad) Mastering	Regular Expressions

Finite Automata?

-	https://sodocumentation.net/regex
-	https://swtch.com/~rsc/regexp/regexp1.html

### Videos
  *   [maththebeautiful - Paul?]( https://www.youtube.com/c/MathTheBeautiful/playlists )
  *   [Statquest - Josh Starmer](https://statquest.org/video-index/)
  *   [Bright Side of Math]( https://www.youtube.com/channel/UCdwo4k1RQHTcq_-WS7Cazqg ) 
  *   [3Blue1Brown](https://www.youtube.com/channel/UCYO_jab_esuFRV4b17AJtAw)
  *     *   [ML videos/text](https://www.3blue1brown.com/topics/neural-networks)
  *   Zedstatistics
  *   [Chris Mack](http://www.lithoguru.com/scientist/statistics/course.html) -
      practical R, models
  *   [Statistics Globe](https://statisticsglobe.com/r-programming-language)
	*		Edward Malthouse - is careful with assumptions.
	*		Prof Christoph Scherber -03
	*		Lorenzo
	*		Sadum
	*		Tom Raby
	*		Jazon Jiao (Alg + Regression)
  *   <https://www.youtube.com/@SerranoAcademy> covariance, intutition! 
  * https://www.youtube.com/watch?v=GFDNF3Zfoa4   - uncorrelation,
    independence, orthogonal Kamlesh Gupta
  * Blargoner duality explained:  https://www.youtube.com/watch?v=eOIJzb7SItg&list=PL6kPvEdcJ4jRnw91XCtlK4UHRHxc0TtsV

<!--
================================================================================================================================
-->


\footnotesize

#### DT Joins (merge)

  -  https://rdatatable.gitlab.io/data.table/index.html
  -  https://stackoverflow.com/questions/1299871/how-to-join-merge-data-frames-inner-outer-left-right?noredirect=1&lq=1
*   [dt, base, tidyverse, clear]<https://jozef.io/r006-merge/>
*   <https://gist.github.com/nacnudus/ef3b22b79164bbf9c0ebafbf558f22a0>
*   <https://stackoverflow.com/questions/1299871/how-to-join-merge-data-frames-inner-outer-left-right>
*   <https://stackoverflow.com/questions/12773822/why-does-xy-join-of-data-tables-not-allow-a-full-outer-join-or-a-left-join>
-  <https://github.com/LucyNjoki/R-LadiesAbuja_Data-Manipulation-with-data.table-in-R/issues/3#issuecomment-1097736781>
-  <https://stackoverflow.com/questions/25430986/create-nested-data-tables-by-collapsing-rows-into-new-data-tables>
-  <https://stackoverflow.com/questions/67261777/data-table-join-is-hard-to-understand>
-  <https://stackoverflow.com/questions/54312225/which-data-table-syntax-for-left-join-one-column-to-prefer/54313203#54313203>
-  <https://rdatatable.gitlab.io/data.table/>
-  <https://themockup.blog/posts/2020-09-04-10-table-rules-in-r/>
-  <https://github.com/TysonStanley/tidyfast>
-  <https://mkmanu.wordpress.com/2016/04/08/working-with-data-frames-in-r-joins-and-merging/>
-  <https://stackoverflow.com/questions/34124928/can-i-use-the-r-data-table-join-capability-to-select-rows-and-perform-some-opera>
-  <https://web.archive.org/web/20131114060032/http://rwiki.sciviews.org/doku.php?id=tips%3adata-frames%3amerge>
-  <https://rpubs.com/ronasta/join_data_tables>
-  <https://johnmackintosh.net/blog/2021-03-22-some-data-table-tips/>
-  <https://rstudio-pubs-static.s3.amazonaws.com/52230_5ae0d25125b544caab32f75f0360e775.html>
-  <https://github.com/ggrothendieck/sqldf#readme>
-  <https://thoughtbot.com/blog/back-to-basics-sql>
-  <https://cran.r-project.org/web/packages/dplyr/vignettes/two-table.html>
-  <https://sqlzoo.net/wiki/The_JOIN_operation>
-  <https://martinctc.github.io/blog/using-data.table-with-magrittr-pipes-best-of-both-worlds/>
-  

### APIs and R


####    Longer Reading/Documentation
  *  [Gargle docs include discussion of a few Google Cloud features](https://gargle.r-lib.org/articles/get-api-credentials.html)
  *  [Mozilla MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP)
  *  [Request body](https://stackoverflow.com/questions/978061/http-get-with-request-body)
  *  https://oauth.com (Aaron Parecki)
  *   web technologies, including RESTFUL, https://www.se.rit.edu/~swen-344/expectations/
  *  [RFC Specs](https://www.rfc-editor.org/)
  *  JSON - https://json-schema.org/

\href{http://www.overleaf.com}{Something Linky} 

####    Videos

  *  \href{https://www.youtube.com/watch?v=TE66McLMMEw}{Anson, Getting Google API/Oauth2 setup.}
  *   [Griffith](https://www.youtube.com/watch?v=iLVoA1DTE60) Curl to make
        resquests.
        ggmaps  Google Maps API https://www.youtube.com/watch?v=Of_M4kcE9yM&list=PLbcglKxZP5PN07Vw-0ukcDJCxFGY2Crgc
  *   [freeCodeCamp](https://www.youtube.com/watch?v=VywxIQ2ZXw4) Postman Intro.
  *   [Oauth 2.0 - Explain like I am 5] (https://www.youtube.com/watch?v=hHRFjbGTEOk)
  *   \url{https://www.youtube.com/watch?v=rhi1eIjSbvkh} Basic Authentication: urlencode, user:pass, how browser responds, TLS
  *   Curl's Creator https://youtu.be/I6id1Y0YuNk?list=PLbcglKxZP5PN07Vw-0ukcDJCxFGY2Crgc
  *   Postman and GitHub: https://youtu.be/AfuL7AFpFmQ?list=PLbcglKxZP5PN07Vw-0ukcDJCxFGY2Crgc
  *   Plumber::,R, api https://www.youtube.com/watch?v=J0Th2QRZ7Rk
	*		R4DS all videos:  https://www.youtube.com/c/R4DSOnlineLearningCommunity

CRAN Task Views:  Web Technology & Services: https://cran.r-project.org/web/views/WebTechnologies.html
  *  (R & Dropbox) https://github.com/karthik/rdrop2 (2020)
  *  (R & Predictit) https://github.com/kiernann/predictr


####	RESTFUL APIS  (see 0300_tech_notes.md)

###	NEOVIM/LUA

####	Config
  *	https://neovim.io/doc/user/quickref.html#option-list
  *	Code Ex:	| Joel | goal: understand ! |https://github.com/whatsthatsmell/dots/tree/master/public%20dots/vim-nvim  
  *	https://cj.rs/blog/my-setup/nvim-0-5/  | go to playlists | view all
	playlists | choose by length, date etc. 
  *	Statusline: https://elianiva.my.id/post/neovim-lua-statusline#active-statusline
  *	https://www.jakewiesler.com/blog/getting-started-with-vim | Jake | good
	but limited.
  *	blog + https://vonheikemen.github.io/devlog/tools/configuring-neovim-using-lua/
  *	blog + https://blog.devgenius.io/create-custom-keymaps-in-neovim-with-lua-d1167de0f2c2
  *	Ex: 	https://gitlab.com/mcepl/vimdir/-/tree/master/plugin	
  *	Ex:	https://github.com/samuelludwig/nixrc/tree/master/modules/user/nvim/lua/dot
  *	300 line challenge: 	https://neovim.discourse.group/t/the-300-line-init-lua-challenge/227
  *	https://benfrain.com/refactor-your-neovim-init-lua-single-file-to-modules-with-packer/
  *	https://github.com/nanotee/nvim-lua-guide
  *	kickstart:  https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua

####	Lua
\begin{enumerate}
  \item https://www.lua.org/manual/5.4/
  \item	http://www.lua.org/pil/contents.html (1st ed)
  \item	https://learnxinyminutes.com/docs/lua/ (learn X in Y)
  \item	http://lua-users.org/wiki/LuaDirectory (lua tutorial, wiki)
	\item Lua by example:		https://luabyexample.org/
\end{enumerate}

####	Plugins

###	Android
- \href{https://www.androidauthority.com/lineageos-install-guide-893303/{decent primer:android RoM" 
- \href{https://developer.android.com/studio/command-line/adb}{adb documentation}

<!--

Rscript -e "rmarkdown::render(<file>, output_format='pdf_document')"
vim:linebreak:nospell:nowrap:cul tw=78 fo=tqlnr foldcolumn=1 cc=+1
-->
